version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/settings.env
    volumes:
      - ./backend/:/app/
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80