CREATE TABLE CONTACT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DATE DATETIME NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    MESSAGE VARCHAR(250) NOT NULL,
    IP BIGINT,
    PRIMARY KEY (ID)
);