CREATE TABLE USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASS VARCHAR(250),
    ROLE VARCHAR(5),
    NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    PRIMARY KEY (ID)
);
